---
confluent_common_repository_baseurl: "https://packages.confluent.io"

confluent_common_repository_debian_baseurl: "{{confluent_common_repository_baseurl}}/deb"
confluent_common_repository_debian_key_url: "{{confluent_common_repository_debian_baseurl}}/{{confluent_repo_version}}/archive.key"
confluent_common_repository_debian_repository: "deb [arch=amd64] {{confluent_common_repository_debian_baseurl}}/{{confluent_repo_version}} stable main"

confluent_common_repository_redhat_baseurl: "{{confluent_common_repository_baseurl}}/rpm"
confluent_common_repository_redhat_main_baseurl: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}"
confluent_common_repository_redhat_main_gpgcheck: 1
confluent_common_repository_redhat_main_gpgkey: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}/archive.key"
confluent_common_repository_redhat_main_enabled: 1

confluent_common_repository_redhat_dist_baseurl: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}/7"
confluent_common_repository_redhat_dist_gpgcheck: 1
confluent_common_repository_redhat_dist_gpgkey: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}/archive.key"
confluent_common_repository_redhat_dist_enabled: 1
confluent_repo_version: 5.5
confluent_package_version: 5.5.1
confluent_full_package_version: "{{ confluent_package_version + '-1' }}"
confluent_package_redhat_suffix: "{{ '-' + confluent_full_package_version if confluent_full_package_version != '' else ''}}"
confluent_package_debian_suffix: "{{ '=' + confluent_full_package_version if confluent_full_package_version != '' else ''}}"
zookeeper_user: "{{zookeeper_default_user}}"
zookeeper_group: "{{zookeeper_default_group}}"
zookeeper_service_name: confluent-zookeeper
zookeeper_main_package: "{{ 'confluent-server' if confluent_server_enabled|bool else 'confluent-kafka-2.12'}}"
zookeeper_packages:
  - confluent-common
  - confluent-rest-utils
  - confluent-metadata-service
  - "{{ zookeeper_main_package }}"
zookeeper_default_user: cp-kafka
zookeeper_default_group: confluent
zookeeper:
  config_file: /etc/kafka/zookeeper.properties
  systemd_file: /usr/lib/systemd/system/{{zookeeper_service_name}}.service
  systemd_override: /etc/systemd/system/{{zookeeper_service_name}}.service.d/override.conf
