zookeeper_service_name: confluent-zookeeper
zookeeper_main_package: confluent-kafka-2.12
zookeeper_packages:
  - confluent-common
  - confluent-rest-utils
  - confluent-metadata-service
  - "{{ zookeeper_main_package }}"

kafka_broker_service_name: confluent-kafka
kafka_broker_main_package: confluent-kafka-2.12
kafka_broker_packages:
  - confluent-common
  - confluent-rest-utils
  - confluent-metadata-service
  - "{{ kafka_broker_main_package }}"
  - confluent-rebalancer
  - confluent-security

kafka_broker_main_package: confluent-kafka-2.12
kafka_connect_service_name: confluent-kafka-connect
kafka_connect_packages:
  - confluent-common
  - confluent-rest-utils
  - confluent-metadata-service
  - "{{ kafka_broker_main_package }}"
  - confluent-kafka-connect-storage-common
  - confluent-kafka-connect-s3
  - confluent-kafka-connect-elasticsearch
  - confluent-kafka-connect-jdbc
  - confluent-kafka-connect-jms
  - confluent-kafka-connect-replicator
  - confluent-security
  - confluent-rebalancer
  - confluent-control-center-fe
  - confluent-control-center
  - confluent-schema-registry
