---
installation_base_path: "/opt/confluent/test"
broker_config_directory: "{{installation_base_path}}/config/properties"

#kafka_broker_final_properties: "{{kafka_broker_properties }}"
#kafka_broker_properties:


