- name: Host Prerequisites
  hosts: zookeeper
  tasks:
  - import_role:
      name: confluent_prerequisites

- name: Zookeeper Provisioning
  hosts: zookeeper
  tags: zookeeper
  tasks:
  - import_role:
      name: confluent_zookeeper

- name: Kafka Broker Provisioning
  hosts: kafka_broker
  tags: kafka_broker
  tasks:
  - import_role:
      name: confluent_kafka_broker


