---
 - name: create folder and extract packages
   hosts: all
   gather_facts: true
   tasks:
   - file:
       path: "/opt/confluent/test"
       state: directory
       mode: "0755"
       
   - unarchive:
       src: "/opt/confluent/confluent-5.5.1-2.12.tar.gz"
       dest: "/opt/confluent/test"
       remote_src: "yes"
       
- name: Kafka Broker Provisioning
  hosts: kafka_broker
  tags: kafka_broker
  tasks:
  - import_role:
      name: confluent_kafka_broker

