---
 - include_role:
    name: confluent_common
 
 - name: create config folder 
   file:
     path: "{{ broker_config_directory }}"
     state: directory
     mode: "0755"
     
 - name: Create Broker config
   template:
      src: server.properties.j2
      dest: "{{ broker_config_directory }}/zookeeper.properties"
