---
 - name: Create config Directory
   file:
     path: "/opt/confluent/test/config/properties"
     state: directory
     mode: "0755"
       
 - name: Create Broker config
   template:
      src: server.properties.j2
      dest: "/opt/confluent/test/config/properties/server.properties"
      
