- name: Zookeeper Upgrade
  # Putting leader group last here with serial=1 so the leader runs last
  hosts: zookeeper
  serial: 1
  tags:
    - upgrade
  tasks:
    - name: Create Backup Directory
      file:
        path: "/tmp/upgrade/{{ zookeeper_service_name }}"
        state: directory
        mode: 0640

    - set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

    - name: Backup Configuration files
      copy:
        src: "{{ item }}"
        remote_src: true
        dest: "/tmp/upgrade/{{ zookeeper_service_name }}/{{ item | basename }}-{{timestamp}}"
      loop:
        - "{{ zookeeper.config_file }}"
        - "{{ zookeeper.systemd_override }}"
        - "{{ kafka_broker.config_file }}"
      # Files cannot be copied because directory is not created in check mode
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Stop Service
      systemd:
        name: "{{ zookeeper_service_name }}"
        state: stopped

    - name: Wait for Zookeeper Status on Another Zookeeper Node
      import_role:
        name: confluent.zookeeper
        tasks_from: health_check.yml
      delegate_to: "{{ groups['zookeeper'] | difference([inventory_hostname]) | first }}"
      when: not ansible_check_mode

    - name: Install the Packages - Red Hat
      yum:
        name: "{{item}}{{confluent_package_redhat_suffix}}"
        state: latest
      loop: "{{ zookeeper_packages }}"
      when: ansible_os_family == "RedHat"
      # Packages will not be found in check mode because repos not changed
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Install the Packages - Debian
      apt:
        name: "{{item}}{{confluent_package_debian_suffix}}"
        update_cache: true
      loop: "{{ zookeeper_packages }}"
      when: ansible_os_family == "Debian"
      # Packages will not be found in check mode because repos not changed
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Put back configuration
      copy:
        dest: "{{ item }}"
        remote_src: true
        src: "/tmp/upgrade/{{ zookeeper_service_name }}/{{ item | basename }}-{{timestamp}}"
      loop:
        - "{{ zookeeper.config_file }}"
        - "{{ kafka_broker.config_file }}"
      # Files cannot be copied because directory is not created in check mode
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Add Disable Admin Server Property
      lineinfile:
        name: "{{zookeeper.config_file}}"
        line: admin.enableServer=false
        regexp: admin.enableServer=.*

    - name: Restart Service
      systemd:
        daemon_reload: true
        name: "{{ zookeeper_service_name }}"
        state: restarted

    - name: Zookeeper Health Check
      import_role:
        name: confluent.zookeeper
        tasks_from: health_check.yml
      when: not ansible_check_mode
